### ISSUE TITLE
Create shell-agnostic secondary UI

### ISSUE THREAD

**Issue by refactorsaurusrex** [refactorsaurusrex/journal-cli#52]
# Summary
Create an alternative UI for `journal-cli` which is shell-agnostic in order to reduce friction for non-Windows users who do not want to install or use PowerShell. 

# Tasks
- [ ] Refactor application into three discrete projects: One for core functionality, another for the PowerShell UI, and the last for a generic cli UI.
- [ ] Determine a distribution process for Mac and Linux users that allows `journal-cli` to be installed directly from a GitHub release. This should include application updates. (Presumption: Windows users will want to stick with the PowerShell UI.)
- [ ] Update build process to attach binaries to GitHub releases.
- [ ] Update documentation website to illustrate both PowerShell and generic installation instructions and functionality.
- [ ] Update GitHub wiki to illustrate both PowerShell and generic commands.
- [ ] Update readme illustrate both PowerShell and generic commands.

**Comment by refactorsaurusrex** [comment]
This has been broken up into several discrete issues which are grouped by [this new milestone](https://github.com/refactorsaurusrex/journal-cli/milestone/1).
